services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  
  scraper:
    build: .
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
